export const NOT_CIRCLE_SIZE = 20;
export const WIRE_WIDTH: number = 7;
export const WIRE_JOINT_MIDDLE: number = 15;
export const WIRE_JOINT_OUTER: number = 5;
export const ELEC_WIDTH: number = WIRE_WIDTH+1;
export const TRUTH_TABLE_BORDER_WIDTH: number = 5;
export const TRUTH_TABLE_DEFAULT_SPEED: number = 0.5; //This is basically a size. It's a size of time.
export const VISUAL_IO_SIZE: number = 50;
export const VISUAL_IO_TEXT_SIZE: number = 25;
export const DEFAULT_FONT_WEIGHT = 700;
export const DEFAULT_FONT_SIZE = 20;